log_level = "warn"
position = "Top"

[modules]
left = [ "Workspaces" ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [ "swaync", "Clock", "Privacy", "Settings" ] ]

[workspaces]
enable_workspace_filling = true

[window_title]
mode = "Title"
truncate_title_after_length = 100

[system_info]
indicators = [ "Cpu", "Memory" ]

[settings]
lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
vpn_more_cmd = "mullvad-vpn"
remove_airplane_btn = true
remove_idle_btn = true
indicators = ["Network", "Vpn", "Audio"]

[[CustomModule]]
name = "swaync"
icon = ""
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -swb"
icons.'dnd.*' = ""
alert = ".*notification"

# Catppuccin Mocha
[appearance]
success_color = "#a6e3a1"
text_color = "#cdd6f4"

workspace_colors = [ "#fab387", "#b4befe", "#cba6f7" ]

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#1e1e2e"
weak = "#313244"
strong = "#45475a"

[appearance.secondary_color]
base = "#11111b"
strong = "#1b1b25"

